export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const REMOVE_NEW_PRODUCT = "REMOVE_NEW_PRODUCT";
export const REMOVE_NEW_PRODUCT_FAIL = "REMOVE_NEW_PRODUCT_FAIL";
